changelog:
  exclude:
    labels:
      - type:mergeback
  categories:
    - title: "Features & Bug Fixes"
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: "Dependency Updates"
      labels:
        - dependencies