spec:
  template:
    spec:
      containers:
        - name: manage-consumables-frontend
          image: ghcr.io/isisbusapps/manage-consumables-frontend@sha256:4587e91716019d8648ba31bdce83e2a79befc604387d10d59181077ee4b46e5e
