spec:
  template:
    spec:
      containers:
        - name: manage-consumables-frontend
          image: ghcr.io/isisbusapps/manage-consumables-frontend@sha256:356e3375c2113cb1d5a8d82bd860ec8abeeef5217f0c4a29779b82a5865d3912
