spec:
  template:
    spec:
      containers:
        - name: manage-consumables-frontend
          image: ghcr.io/isisbusapps/manage-consumables-frontend@sha256:3e968d14a422d64290b6abd2a549780132458949ee008f508654bd66f07d1c95
