spec:
  template:
    spec:
      containers:
        - name: manage-consumables-backend
          image: ghcr.io/isisbusapps/manage-consumables-backend@sha256:e5d8b56d2d80246ad3a6def915cf8ca3d1531ea4f5b95c1d276e5fa6c7131564
