spec:
  template:
    spec:
      containers:
        - name: manage-consumables-backend
          image: ghcr.io/isisbusapps/manage-consumables-backend@sha256:a858aee217b74787243a4c91a8e6a9dd34df417165cd44b45c904da0a1f293b5
